# Generated by Django 5.2.1 on 2025-05-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
