# Generated by Django 5.2.1 on 2025-05-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='UserInfo',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_type',
            new_name='type',
        ),
    ]
