# Generated by Django 5.2.1 on 2025-05-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
