# Generated by Django 5.2.1 on 2025-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userinfo_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='course',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee')], max_length=100, null=True),
        ),
    ]
