# Generated by Django 5.2.1 on 2025-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userinfo_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
